// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook_file.proto

package com.example.kotlin_basic.proto;

public final class AddressbookFile {
  private AddressbookFile() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_kotlin_basic_proto_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_kotlin_basic_proto_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_kotlin_basic_proto_Person_PhoneNumber_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_kotlin_basic_proto_Person_PhoneNumber_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_kotlin_basic_proto_AddressBook_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_kotlin_basic_proto_AddressBook_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026addressbook_file.proto\022\036com.example.ko" +
      "tlin_basic.proto\032\037google/protobuf/timest" +
      "amp.proto\"\302\002\n\006Person\022\014\n\004name\030\001 \001(\t\022\n\n\002id" +
      "\030\002 \001(\005\022\022\n\005email\030\003 \001(\tH\000\210\001\001\022B\n\006phones\030\004 \003" +
      "(\01322.com.example.kotlin_basic.proto.Pers" +
      "on.PhoneNumber\0220\n\014last_updated\030\005 \001(\0132\032.g" +
      "oogle.protobuf.Timestamp\032]\n\013PhoneNumber\022" +
      "\016\n\006number\030\001 \001(\t\022>\n\004type\030\002 \001(\01620.com.exam" +
      "ple.kotlin_basic.proto.Person.PhoneType\"" +
      "+\n\tPhoneType\022\n\n\006MOBILE\020\000\022\010\n\004HOME\020\001\022\010\n\004WO" +
      "RK\020\002B\010\n\006_email\"E\n\013AddressBook\0226\n\006people\030" +
      "\001 \003(\0132&.com.example.kotlin_basic.proto.P" +
      "ersonB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_com_example_kotlin_basic_proto_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_kotlin_basic_proto_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_kotlin_basic_proto_Person_descriptor,
        new java.lang.String[] { "Name", "Id", "Email", "Phones", "LastUpdated", "Email", });
    internal_static_com_example_kotlin_basic_proto_Person_PhoneNumber_descriptor =
      internal_static_com_example_kotlin_basic_proto_Person_descriptor.getNestedTypes().get(0);
    internal_static_com_example_kotlin_basic_proto_Person_PhoneNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_kotlin_basic_proto_Person_PhoneNumber_descriptor,
        new java.lang.String[] { "Number", "Type", });
    internal_static_com_example_kotlin_basic_proto_AddressBook_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_kotlin_basic_proto_AddressBook_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_kotlin_basic_proto_AddressBook_descriptor,
        new java.lang.String[] { "People", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
