// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook_file.proto

package com.example.kotlin_basic.proto;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.kotlin_basic.proto.AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.example.kotlin_basic.proto.Person people = 1;</code>
   */
  java.util.List<com.example.kotlin_basic.proto.Person> 
      getPeopleList();
  /**
   * <code>repeated .com.example.kotlin_basic.proto.Person people = 1;</code>
   */
  com.example.kotlin_basic.proto.Person getPeople(int index);
  /**
   * <code>repeated .com.example.kotlin_basic.proto.Person people = 1;</code>
   */
  int getPeopleCount();
  /**
   * <code>repeated .com.example.kotlin_basic.proto.Person people = 1;</code>
   */
  java.util.List<? extends com.example.kotlin_basic.proto.PersonOrBuilder> 
      getPeopleOrBuilderList();
  /**
   * <code>repeated .com.example.kotlin_basic.proto.Person people = 1;</code>
   */
  com.example.kotlin_basic.proto.PersonOrBuilder getPeopleOrBuilder(
      int index);
}
