/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import java.io.*;

public class App {
    public static void main(String[] args) throws Exception {
        App app = new App();
//        System.out.println(app.getGreeting());
        app.protoWrite(args);
        app.protoRead(args);
    }

    private void protoRead(String[] args) throws IOException {
        if (args.length != 1) {
            // this is wrong. but whatever just a tutorial
            System.err.println("Usage: ListPeople ADDRESS_BOOK_LIST");
            System.exit(-1);
        }
        AddressBook addressBook = AddressBook.parseFrom(new FileInputStream(args[0]));
        ListPeople.print(addressBook);
    }

    public String getGreeting() {
        return "Hello World!";
    }

    private void protoWrite(String[] args) throws Exception {
        if (args.length != 1) {
            System.err.println("Usage AddPerson ADDRESS_BOOK_FILE");
            System.exit(-1);
        }
        AddressBook.Builder addressBook = AddressBook.newBuilder();

        // Read the existing address book
        try {
            addressBook.mergeFrom(new FileInputStream(args[0]));
        } catch (FileNotFoundException e) {
            System.out.println(args[0] + ": file not found. Creating new file.");
        }

        // add an address
        addressBook.addPerson(
                AddPerson.promptForAddress(
                        new BufferedReader(new InputStreamReader(System.in)), System.out));

        // Write the new address book back to disk
        FileOutputStream output = new FileOutputStream(args[0]);
        addressBook.build().writeTo(output);
        output.close();
    }


    public void test() {
        Person person = Person.newBuilder()
                .setId(1234)
                .setName("John Doe")
                .setEmail("jdoe@example.com")
                .addPhones(
                        Person.PhoneNumber.newBuilder()
                                .setNumber("555-4321")
                                .setType(Person.PhoneType.HOME)
                )
                .build();

        System.out.println("Person " + person);
    }
}
