//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: addressbook_file.proto

package com.example.kotlin_basic.proto;

@kotlin.jvm.JvmName("-initializeaddressBook")
inline fun addressBook(block: com.example.kotlin_basic.proto.AddressBookKt.Dsl.() -> kotlin.Unit): com.example.kotlin_basic.proto.AddressBook =
  com.example.kotlin_basic.proto.AddressBookKt.Dsl._create(com.example.kotlin_basic.proto.AddressBook.newBuilder()).apply { block() }._build()
object AddressBookKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: com.example.kotlin_basic.proto.AddressBook.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.kotlin_basic.proto.AddressBook.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.kotlin_basic.proto.AddressBook = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class PeopleProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .com.example.kotlin_basic.proto.Person people = 1;</code>
     */
     val people: com.google.protobuf.kotlin.DslList<com.example.kotlin_basic.proto.Person, PeopleProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getPeopleList()
      )
    /**
     * <code>repeated .com.example.kotlin_basic.proto.Person people = 1;</code>
     * @param value The people to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addPeople")
    fun com.google.protobuf.kotlin.DslList<com.example.kotlin_basic.proto.Person, PeopleProxy>.add(value: com.example.kotlin_basic.proto.Person) {
      _builder.addPeople(value)
    }
    /**
     * <code>repeated .com.example.kotlin_basic.proto.Person people = 1;</code>
     * @param value The people to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignPeople")
    @Suppress("NOTHING_TO_INLINE")
    inline operator fun com.google.protobuf.kotlin.DslList<com.example.kotlin_basic.proto.Person, PeopleProxy>.plusAssign(value: com.example.kotlin_basic.proto.Person) {
      add(value)
    }
    /**
     * <code>repeated .com.example.kotlin_basic.proto.Person people = 1;</code>
     * @param values The people to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllPeople")
    fun com.google.protobuf.kotlin.DslList<com.example.kotlin_basic.proto.Person, PeopleProxy>.addAll(values: kotlin.collections.Iterable<com.example.kotlin_basic.proto.Person>) {
      _builder.addAllPeople(values)
    }
    /**
     * <code>repeated .com.example.kotlin_basic.proto.Person people = 1;</code>
     * @param values The people to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllPeople")
    @Suppress("NOTHING_TO_INLINE")
    inline operator fun com.google.protobuf.kotlin.DslList<com.example.kotlin_basic.proto.Person, PeopleProxy>.plusAssign(values: kotlin.collections.Iterable<com.example.kotlin_basic.proto.Person>) {
      addAll(values)
    }
    /**
     * <code>repeated .com.example.kotlin_basic.proto.Person people = 1;</code>
     * @param index The index to set the value at.
     * @param value The people to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setPeople")
    operator fun com.google.protobuf.kotlin.DslList<com.example.kotlin_basic.proto.Person, PeopleProxy>.set(index: kotlin.Int, value: com.example.kotlin_basic.proto.Person) {
      _builder.setPeople(index, value)
    }
    /**
     * <code>repeated .com.example.kotlin_basic.proto.Person people = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearPeople")
    fun com.google.protobuf.kotlin.DslList<com.example.kotlin_basic.proto.Person, PeopleProxy>.clear() {
      _builder.clearPeople()
    }

  }
}
@kotlin.jvm.JvmSynthetic
inline fun com.example.kotlin_basic.proto.AddressBook.copy(block: com.example.kotlin_basic.proto.AddressBookKt.Dsl.() -> kotlin.Unit): com.example.kotlin_basic.proto.AddressBook =
  com.example.kotlin_basic.proto.AddressBookKt.Dsl._create(this.toBuilder()).apply { block() }._build()

